//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyJob_ProDG.UI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,0,0,0")]
        public global::System.Windows.Rect WindowPosition {
            get {
                return ((global::System.Windows.Rect)(this["WindowPosition"]));
            }
            set {
                this["WindowPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool WindowStateMaximized {
            get {
                return ((bool)(this["WindowStateMaximized"]));
            }
            set {
                this["WindowStateMaximized"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ContainerDataTableDisplayIndex {
            get {
                return ((string)(this["ContainerDataTableDisplayIndex"]));
            }
            set {
                this["ContainerDataTableDisplayIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ContainerDataTableWidth {
            get {
                return ((string)(this["ContainerDataTableWidth"]));
            }
            set {
                this["ContainerDataTableWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ContainerDataTableVisibilities {
            get {
                return ((string)(this["ContainerDataTableVisibilities"]));
            }
            set {
                this["ContainerDataTableVisibilities"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ReeferDataTableDisplayIndex {
            get {
                return ((string)(this["ReeferDataTableDisplayIndex"]));
            }
            set {
                this["ReeferDataTableDisplayIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ReeferDataTableWidth {
            get {
                return ((string)(this["ReeferDataTableWidth"]));
            }
            set {
                this["ReeferDataTableWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ReeferDataTableVisibilities {
            get {
                return ((string)(this["ReeferDataTableVisibilities"]));
            }
            set {
                this["ReeferDataTableVisibilities"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public double ConflictsWidth {
            get {
                return ((double)(this["ConflictsWidth"]));
            }
            set {
                this["ConflictsWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1,1,2,3,4,5,6")]
        public string ExcelReeferTemplate {
            get {
                return ((string)(this["ExcelReeferTemplate"]));
            }
            set {
                this["ExcelReeferTemplate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Working cargo plan.ejc")]
        public string WorkingCargoPlanFile {
            get {
                return ((string)(this["WorkingCargoPlanFile"]));
            }
            set {
                this["WorkingCargoPlanFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DgDataTableDisplayIndex {
            get {
                return ((string)(this["DgDataTableDisplayIndex"]));
            }
            set {
                this["DgDataTableDisplayIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DgDataTableWidth {
            get {
                return ((string)(this["DgDataTableWidth"]));
            }
            set {
                this["DgDataTableWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DgDataTableVisibilities {
            get {
                return ((string)(this["DgDataTableVisibilities"]));
            }
            set {
                this["DgDataTableVisibilities"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FirstTimeStart {
            get {
                return ((bool)(this["FirstTimeStart"]));
            }
            set {
                this["FirstTimeStart"] = value;
            }
        }
    }
}
