//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyJob_ProDG.UI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.13.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,0,0,0")]
        public global::System.Windows.Rect WindowPosition {
            get {
                return ((global::System.Windows.Rect)(this["WindowPosition"]));
            }
            set {
                this["WindowPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool WindowStateMaximized {
            get {
                return ((bool)(this["WindowStateMaximized"]));
            }
            set {
                this["WindowStateMaximized"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ContainerDataTableDisplayIndex {
            get {
                return ((string)(this["ContainerDataTableDisplayIndex"]));
            }
            set {
                this["ContainerDataTableDisplayIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Auto")]
        public string ContainerDataTableWidth {
            get {
                return ((string)(this["ContainerDataTableWidth"]));
            }
            set {
                this["ContainerDataTableWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ContainerDataTableVisibilities {
            get {
                return ((string)(this["ContainerDataTableVisibilities"]));
            }
            set {
                this["ContainerDataTableVisibilities"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ReeferDataTableDisplayIndex {
            get {
                return ((string)(this["ReeferDataTableDisplayIndex"]));
            }
            set {
                this["ReeferDataTableDisplayIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Auto")]
        public string ReeferDataTableWidth {
            get {
                return ((string)(this["ReeferDataTableWidth"]));
            }
            set {
                this["ReeferDataTableWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ReeferDataTableVisibilities {
            get {
                return ((string)(this["ReeferDataTableVisibilities"]));
            }
            set {
                this["ReeferDataTableVisibilities"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public double ConflictsWidth {
            get {
                return ((double)(this["ConflictsWidth"]));
            }
            set {
                this["ConflictsWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Working cargo plan.ejc")]
        public string WorkingCargoPlanFile {
            get {
                return ((string)(this["WorkingCargoPlanFile"]));
            }
            set {
                this["WorkingCargoPlanFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DgDataTableDisplayIndex {
            get {
                return ((string)(this["DgDataTableDisplayIndex"]));
            }
            set {
                this["DgDataTableDisplayIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Auto")]
        public string DgDataTableWidth {
            get {
                return ((string)(this["DgDataTableWidth"]));
            }
            set {
                this["DgDataTableWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DgDataTableVisibilities {
            get {
                return ((string)(this["DgDataTableVisibilities"]));
            }
            set {
                this["DgDataTableVisibilities"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FirstTimeStart {
            get {
                return ((bool)(this["FirstTimeStart"]));
            }
            set {
                this["FirstTimeStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ExcelReeferTemplate1 {
            get {
                return ((string)(this["ExcelReeferTemplate1"]));
            }
            set {
                this["ExcelReeferTemplate1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ExcelReeferTemplate2 {
            get {
                return ((string)(this["ExcelReeferTemplate2"]));
            }
            set {
                this["ExcelReeferTemplate2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ExcelReeferTemplate3 {
            get {
                return ((string)(this["ExcelReeferTemplate3"]));
            }
            set {
                this["ExcelReeferTemplate3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ExcelReeferTemplate4 {
            get {
                return ((string)(this["ExcelReeferTemplate4"]));
            }
            set {
                this["ExcelReeferTemplate4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ExcelReeferTemplate5 {
            get {
                return ((string)(this["ExcelReeferTemplate5"]));
            }
            set {
                this["ExcelReeferTemplate5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public byte SelectedExcelReeferTemplate {
            get {
                return ((byte)(this["SelectedExcelReeferTemplate"]));
            }
            set {
                this["SelectedExcelReeferTemplate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ExcelDgTemplate1 {
            get {
                return ((string)(this["ExcelDgTemplate1"]));
            }
            set {
                this["ExcelDgTemplate1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ExcelDgTemplate2 {
            get {
                return ((string)(this["ExcelDgTemplate2"]));
            }
            set {
                this["ExcelDgTemplate2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ExcelDgTemplate3 {
            get {
                return ((string)(this["ExcelDgTemplate3"]));
            }
            set {
                this["ExcelDgTemplate3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ExcelDgTemplate4 {
            get {
                return ((string)(this["ExcelDgTemplate4"]));
            }
            set {
                this["ExcelDgTemplate4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ExcelDgTemplate5 {
            get {
                return ((string)(this["ExcelDgTemplate5"]));
            }
            set {
                this["ExcelDgTemplate5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public byte SelectedExcelDgTemplate {
            get {
                return ((byte)(this["SelectedExcelDgTemplate"]));
            }
            set {
                this["SelectedExcelDgTemplate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowSummaryOnUpdateCondition {
            get {
                return ((bool)(this["ShowSummaryOnUpdateCondition"]));
            }
            set {
                this["ShowSummaryOnUpdateCondition"] = value;
            }
        }
    }
}
